apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: mqstorage-org
  owner: mqstorage-org
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/mqstorage-org/multi-tenancy-gitops-apps.git
